<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FlightBooking.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FlightBooking.Domain\FlightBooking.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Services\AuthService.cs" />
    </ItemGroup>

</Project>
